### ISSUE TITLE
`OpenAIError: The api_key client option must be set` Error on Initial Library Import

### ISSUE THREAD

**Issue by parkervg** [target-benchmark/target#31]
**Is your feature request related to a problem? Please describe.**
When trying to get the library up and running (`from target_benchmark.evaluators import TARGET`), I was thinking I could use a small local embedding model to test it out ([example](https://huggingface.co/TaylorAI/gte-tiny)). Instead, I hit this error: 

```
OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable 
```

**Describe the solution you'd like**
I think it would be nice to initialize the OpenAI client [here](https://github.com/target-benchmark/target/blob/main/target_benchmark/retrievers/llama_index/embedding_utils.py#L39) lazily, so only when the user imports and uses a retriever that has a dependency on OpenAI do you require the environment variable to be set. That way, if e.g. Anthropic models are supported in the future, env variable requirements are self-contained within their respective class initializations.

**Comment by madelonhulsebos** [comment]
Thanks for the suggestion @parkervg! @jixy2012 what do you think? While it might not be urgent, I think it would be very good to support this model flexibility later.
